### ISSUE TITLE
Carp

### ISSUE THREAD

**Issue by eriksvedang** [makuto/cakelisp#1]
Hi, nice looking language! Please don't list Carp as not under development though, we're pretty active :) 

Cheers

**Comment by eriksvedang** [comment]
Thanks! And good luck with your language!

**Comment by makuto** [comment]
My apologies for the mistake. I think I must've checked some other repository and mis-attributed Carp's development activity to it.

Keep up the good work! Carp was one of my influences in creating Cakelisp.
