### ISSUE TITLE
Clarifying GPLv3 only or GPLv3+

### ISSUE THREAD

**Issue by sbond75** [makuto/cakelisp#2]
Hello,

I am working on packaging cakelisp for Nix, a package manager. I found out that there are two different forms of GPLv3. The GPLv3+ (also known as "GPL 3 or later") will incorporate future GPL license versions into the requirements for the license. The maintainers at Nixpkgs want me to clarify if you want to use GPLv3+ or GPLv3 only. For more info, see [this website](https://www.gnu.org/licenses/identify-licenses-clearly.en.html).

**Comment by makuto** [comment]
Thank you for packaging Cakelisp! Let me know if you need any additional help.

**Comment by makuto** [comment]
(in that checkin, I added SPDX identifier `GPL-3.0-or-later`)
