### ISSUE TITLE
Build Cakelisp on macOS

### ISSUE THREAD

**Issue by bentxt** [makuto/cakelisp#4]
Hi,
I try to build Cakelisp on macOS BigSur (11.1), I've tried a few things (messed with build.sh) but I don't get past the bootstrap compiler. But lets start with unmodified sources

```
git clone https://github.com/makuto/cakelisp
cd cakelisp
sh Build.sh 2> err.log
```
[err.log](https://github.com/makuto/cakelisp/files/5849660/err.log)

this gives me errors like 

```
...
34 src/Evaluator.cpp:165:42: error: no member named 'emplace' in 'std::__1::unordered_map<std::__    1::basic_string<char>, ObjectReferenceStatus, std::__1::hash<std::__1::basic_string<char> >, s    td::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std    ::__1::basic_string<char>, ObjectReferenceStatus> > >'
 35                             findDefinition->second.references.emplace(
 36                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
 37 src/Evaluator.cpp:340:42: error: expected expression
 38                                 definition.macroExpansions.push_back({&invocationStart, macroO    utputTokens});
...
245 src/Generators.cpp:1865:43: error: expected expression
246         generatorBodyContext.delimiterTemplate = {};
....

```

**Comment by bentxt** [comment]
and here is what I try in a second step, which is messing with the build.sh script

```
head Build.sh
#!/bin/sh

CAKELISP_BOOTSTRAP_BIN=bin/cakelisp_bootstrap
CC=g++
LINK=g++
```

```
g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

So, lets replace g++ with gcc-10:

**Comment by bentxt** [comment]
```
gcc-10 -v
Using built-in specs.
COLLECT_GCC=gcc-10
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/10.2.0_2/libexec/gcc/x86_64-apple-darwin20/10.2.0/lto-wrapper
Target: x86_64-apple-darwin20
Configured with: ../configure --build=x86_64-apple-darwin20 --prefix=/usr/local/Cellar/gcc/10.2.0_2 --libdir=/usr/local/Cellar/gcc/10.2.0_2/lib/gcc/10 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-10 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 10.2.0_2' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk SED=/usr/bin/sed
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (Homebrew GCC 10.2.0_2)
```

```
head Build.sh
#!/bin/sh

CAKELISP_BOOTSTRAP_BIN=bin/cakelisp_bootstrap
CC=g++-10
LINK=g++-10
```

```
sh ./build.sh
bin/cakelisp_bootstrap does not exist. Building bootstrap executable manually
ld: unknown option: --export-dynamic
collect2: error: ld returned 1 exit status
```

Ok, lets replace --export-dynamic with -rdynamic

```
 36   $LINK -o $CAKELISP_BOOTSTRAP_BIN *.o -ldl -rdynamic || exit $?
 37   #$LINK -o $CAKELISP_BOOTSTRAP_BIN *.o -ldl -Wl,--export-dynamic || exit $?
```

And run build.sh again
```
sh ./build.sh 2> err
bin/cakelisp_bootstrap exists. Building using Cakelisp
```

Again logs of errors, see again err.log
[err.log](https://github.com/makuto/cakelisp/files/5849712/err.log)

**Comment by makuto** [comment]
Good morning, and thanks for all the effort you've put in so far!

You are very close to having it all working. Those errors appear to be a problem with the compile-time C++ compiler - I use C++11 features like initializer lists, but they don't seem to be accepted by the compiler.

If you open `Bootstrap_MSVC.cake`, you can see the syntax for overriding the compile-time compiler:

```lisp
(add-build-options "/nologo" "/DWINDOWS" "/DCAKELISP_EXPORTING" "/EHsc"
                   ;;; DEBUG ONLY! Note that link also needs /DEBUG
                   "/Zi" "/FS" "/Fd:bin\cakelisp.pdb" "/DEBUG:FASTLINK" "/MDd")

(set-cakelisp-option build-time-compiler "cl.exe")
(set-cakelisp-option build-time-compile-arguments
                     "/c" 'source-input 'object-output
                     'include-search-dirs 'additional-options)
```

You'll need to do similarly in `Bootstrap.cake`, with the appropriate compiler and compiler options. Do this for both the `build-time-compiler` and `compile-time-compiler`. There is some documentation on the build system [here](https://github.com/makuto/cakelisp/blob/master/doc/Cakelisp.org#example-bootstrap).

Alternatively, you can instead change the hard-coded defaults in `src/ModuleManager.cpp`, [line 128](https://github.com/makuto/cakelisp/blob/master/src/ModuleManager.cpp#L128), though you will need to delete and rebuild `cakelisp_bootstrap`. Whichever approach seems easier to you works for me.

You can iterate on which options are necessary via running the command directly:

```sh
/usr/bin/g++ -g -c cakelisp_cache/comptime_cakelisp_link_hook.cpp -o cakelisp_cache/comptime_cakelisp_link_hook.o -Isrc/ -fPIC
```
(Cakelisp always outputs the full command line of any process which returns non-zero exit, which gives you an easier way to try different commands before hooking them up to cakelisp.) Once you get that one file compiling, you can copy the changes over to the `Bootstrap.cake` or `src/ModuleManager.cpp` compiler defaults.

If the compiler overriding part is too hard, I can do it for you, once you send me the working compile command for that `cakelisp_cache/comptime_cakelisp_link_hook.cpp`. (I don't have a mac I can test on, unfortunately.)

**Comment by bentxt** [comment]
thanks for your directions, I have now a working compiler thanks to the following quick edits

in Bootstrap.cake:

change '-Wl,--export-dynamic' to '-rdynamic'

in src/ModuleManager.cpp:
change to` manager.environment.compileTimeBuildCommand.fileToExecute = "/usr/local/bin/g++-10`

**Comment by bentxt** [comment]
just to add: I think this changes are just quick fixes, better would be 'build-time-compiler' in the bootstrap script, but I'm not so brave yet.

the other issue is with hot reloading, I think this won't work either ... lets see

**Comment by makuto** [comment]
I just tested hot-reloading, and it does currently have an issue. If you run `./hot_loader`, you'll get an error:

```
./hot_loader: symbol lookup error: ./libHotReloadingTemp_1.so: undefined symbol: hotReloadFindVariable
```
This is fixed by adding the following line to the top of `runtime/HotReloading.cake`:

```lisp
(set-cakelisp-option use-c-linkage true)
```
You also need to add `runtime/Config_Linux.cake` to `BuildHotReloadLib.sh`.

Then, you should be able to run:
```sh
./BuildAndRunTests.sh
./BuildHotReloadLib.sh
./hot_loader
```
If you see the text adventure prompt, you can open `runtime/TextAdventure.cake` and make a change, run `./BuildHotReloadLib.sh`, then enter `r` in the text adventure to reload.

This process is a bit involved right now, but it'll be possible to make it streamlined in the future.

**Comment by makuto** [comment]
`BuildAndRunTests.sh` will probably fail due to the cross-compilation test. Here's what you should run to do a hot-reloading test:
```sh
./bin/cakelisp runtime/Config_Linux.cake runtime/HotReloadingCodeModifier.cake runtime/TextAdventure.cake
./bin/cakelisp runtime/Config_Linux.cake runtime/HotLoader.cake
./hot_loader
```
Then, while the game is running, after changing `runtime/TextAdventure.cake` (I typically change the message line 43 to give myself an easy confirmation), run:
```sh
./bin/cakelisp runtime/Config_Linux.cake runtime/HotReloadingCodeModifier.cake runtime/TextAdventure.cake
```
And enter `r` to reload with your change.

**Comment by makuto** [comment]
The macOS branch should work out-of-the-box for building on Mac. I'm still working on cleaning it up, but I should be merging it into master relatively soon (this month or so).

**Comment by bentxt** [comment]
Hi again , 
I would like to take another test ride with cakelisp on my mac. 
The main branch is still failing and the 'macos' branch is somewhat behind.
What is you advice?
Thanks
Ben

**Comment by makuto** [comment]
Hi,
I just updated macOS with the latest changes from main. Can you try that branch out? If it works, I'll finish merging it into main. Otherwise, we'll work through any remaining issues here :).

**Comment by makuto** [comment]
Oh, and make sure to delete your `bin` and `cakelisp_cache` directories as some changes in main required a fresh build. This usually doesn't need to be done.

**Comment by bentxt** [comment]
ahh sorry, that was the main branch. 

Let me try the macos branch then

$ sh build_mac.sh

sh ./Build_Mac.sh
bin/cakelisp_bootstrap does not exist. Building bootstrap executable manually
Built bin/cakelisp_bootstrap successfully. Now building with Cakelisp
Undefined symbols for architecture x86_64:
  "printBuiltInGeneratorMetadata(EvaluatorEnvironment*)", referenced from:
      _main in Main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
clang -o cakelisp_cache/Bootstrap/cakelisp cakelisp_cache/Bootstrap/Tokenizer.cpp.o cakelisp_cache/Bootstrap/Evaluator.cpp.o cakelisp_cache/Bootstrap/Utilities.cpp.o cakelisp_cache/Bootstrap/FileUtilities.cpp.o cakelisp_cache/Bootstrap/Converters.cpp.o cakelisp_cache/Bootstrap/Writer.cpp.o cakelisp_cache/Bootstrap/Generators.cpp.o cakelisp_cache/Bootstrap/GeneratorHelpers.cpp.o cakelisp_cache/Bootstrap/RunProcess.cpp.o cakelisp_cache/Bootstrap/OutputPreambles.cpp.o cakelisp_cache/Bootstrap/DynamicLoader.cpp.o cakelisp_cache/Bootstrap/ModuleManager.cpp.o cakelisp_cache/Bootstrap/Logging.cpp.o cakelisp_cache/Bootstrap/Build.cpp.o cakelisp_cache/Bootstrap/Main.cpp.o -ldl -lstdc++

**Comment by makuto** [comment]
Try it with 76631da.

**Comment by makuto** [comment]
I had added a file in the interim that the Mac build scripts didn't have yet.

**Comment by makuto** [comment]
macOS is now merged into master, so that makes things easier for us!

**Comment by bentxt** [comment]
thank you. From the outside everything looks great so far:
```

(master)> sh ./Build_Mac.sh
bin/cakelisp_bootstrap does not exist. Building bootstrap executable manually
Built bin/cakelisp_bootstrap successfully. Now building with Cakelisp
Successfully built and linked bin/cakelisp
Cakelisp successfully bootstrapped. Use ./bin/cakelisp to build your files
[I] ben@moonraker ~/h/c/cakelisp (master)> ls bin/
cakelisp           cakelisp_bootstrap
```

**Comment by bentxt** [comment]
a first hello runs fine

 ./bin/cakelisp --execute test/Hello.cake
No changes needed for test/Hello
Hello, world! From Cakelisp!
1
2
3

**Comment by makuto** [comment]
Great, thanks for your patience getting this working!
