### ISSUE TITLE
Raylib bindings? 

### ISSUE THREAD

**Issue by MetalMaxMX** [makuto/cakelisp#8]
So hi! Very curious about what you're doing there with Cakelisp. This is more of a feature request but I was wondering if you could consider adding bindings to the Raylib project (https://github.com/raysan5/raylib) as its API is written in C and I think could make a great addition there. 

Cheers!
MetalMaxMX.

**Comment by makuto** [comment]
It's in gamelib now! https://macoy.me/code/macoy/gamelib/src/branch/master/src/Raylib.cake

**Comment by makuto** [comment]
I was able to set it up in 20 minutes. It's nice and simple!
